### ISSUE TITLE
Plotting function does not really remember p-value threshold

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#37]
When you plot again, the custom threshold chosen for p-value is shown correctly. However, when plotting, it seems to use the default 0.05 threshold. It is only updated once you change the value in the edit box. 

I would advise to not remember the value and have users change it manually every time they summon the GUI to avoid confusion.

1. Call 2nd level analysis

2. Change p-value threshold

3. Image all

4. Close GUI

5. Open GUI again - the p-value threshold set in 1 is remembered and shown in the p-value edit box

6. Image all (this uses the default 0.05 threshold not the p-value in the edit box)

**Comment by CPernet** [comment]
i do not understand 'When you plot again, the custom threshold chosen for p-value is shown correctly. However, when plotting, it seems to use the default 0.05 threshold. It is only updated once you change the value in the edit box.' 

when replotting it uses by default the cache (the last value/plot done) - and yes update only if change the value, otherwise this is the same and thus correct  ;; if allows not have to recompte max stats and clusters each time, as requested few years back 

don't get the 1st/2nd level ting either, sorry -- the only default is thresholding in limo_results

**Comment by arnodelorme** [comment]
It is a GUI problem. Changing the value in the edit box does not change the p-value. It is a callback issue and communication between the GUI and back end problem. Try the 6 steps I outlined.

**Comment by CPernet** [comment]
it does but you need to press enter -- i see your point

**Comment by CPernet** [comment]
ok I did change it -- but OMG this is an annoying behaviour (see commented line in limo_results.m line 89+) - each time have to reselect the threshold when looking at eg an ANOVA with multiple results is painful -- as I said usually the threshold is kept but on occasion it is not and that's what we need to find out ; not resetting the GUI

**Comment by arnodelorme** [comment]
Wonderful. Thanks,

Arno

**Comment by CPernet** [comment]
i meant the code is there but commented -- this is not user friendly ie we need to find another solution ; 1st documenting more precisely when this happens (because for me it usually doesn't)
